theme:
  name: material
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/weather-night
      name: change to dark mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: change to light mode
  features:
  - announce.dismiss
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - content.tabs.link
  - content.tooltips
  - header.autohide
  - navigation.expand
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.prune
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
markdown_extensions:
- admonition
- def_list
- footnotes
- abbr
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- md_in_html
- pymdownx.arithmatex:
    generic: true
- toc:
    permalink: true
    toc_depth: 3
- pymdownx.highlight:
    anchor_linenums: true
    linenums: true
    use_pygments: true
    pygments_lang_class: true
    auto_title: true
    linenums_style: pymdownx-inline
- pymdownx.betterem
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.keys
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.magiclink
- pymdownx.smartsymbols
- pymdownx.snippets
- pymdownx.tasklist:
    custom_checkbox: true
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji ''
    emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
    combine_header_slug: true
- pymdownx.tasklist:
    custom_checkbox: true
    clickable_checkbox: true
- meta
- tables
site_name: Python-Motion-Planning
site_description: Motion planning algorithms for Python.
site_author: Yang Haodong, Wu Maojia
site_url: http://localhost:8000
use_directory_urls: false
copyright: Copyright @ 2023-2024, Yang Haodong, Wu Maojia.
repo_url: https://github.com/ai-winter/python_motion_planning/
nav:
- Home: index.md
- common:
  - geometry:
    - collision:
      - CollisionChecker: common\geometry\collision\CollisionChecker.md
    - curve_generation:
      - bezier_curve:
        - Bezier: common\geometry\curve_generation\bezier_curve\Bezier.md
        - Bernstein: common\geometry\curve_generation\bezier_curve\Bernstein.md
      - bspline_curve:
        - BSpline: common\geometry\curve_generation\bspline_curve\BSpline.md
      - cubic_spline:
        - CubicSpline: common\geometry\curve_generation\cubic_spline\CubicSpline.md
      - curve:
        - Curve: common\geometry\curve_generation\curve\Curve.md
      - curve_factory:
        - CurveFactory: common\geometry\curve_generation\curve_factory\CurveFactory.md
      - dubins_curve:
        - Dubins: common\geometry\curve_generation\dubins_curve\Dubins.md
      - polynomial_curve:
        - QuinticPolynomial: common\geometry\curve_generation\polynomial_curve\QuinticPolynomial.md
        - Polynomial: common\geometry\curve_generation\polynomial_curve\Polynomial.md
      - reeds_shepp:
        - ReedsShepp: common\geometry\curve_generation\reeds_shepp\ReedsShepp.md
    - line_segment2d:
      - LineSegment2d: common\geometry\line_segment2d\LineSegment2d.md
    - point:
      - Point2d: common\geometry\point\Point2d.md
      - Point3d: common\geometry\point\Point3d.md
    - vector2d:
      - Vec2d: common\geometry\vector2d\Vec2d.md
  - math:
    - math_helper:
      - MathHelper: common\math\math_helper\MathHelper.md
  - structure:
    - agent:
      - Agent: common\structure\agent\Agent.md
      - DiffRobot: common\structure\agent\DiffRobot.md
    - env:
      - Env: common\structure\env\Env.md
      - Grid: common\structure\env\Grid.md
    - node:
      - Node: common\structure\node\Node.md
  - utils:
    - logger:
      - Logger: common\utils\logger\Logger.md
    - params_manager:
      - ParamsManager: common\utils\params_manager\ParamsManager.md
    - visualization:
      - Visualizer: common\utils\visualization\Visualizer.md
- controller:
  - apf:
    - APF: controller\apf\APF.md
  - control_factory:
    - ControlFactory: controller\control_factory\ControlFactory.md
  - controller:
    - Controller: controller\controller\Controller.md
  - dwa:
    - DWA: controller\dwa\DWA.md
  - lqr:
    - LQR: controller\lqr\LQR.md
  - mpc:
    - MPC: controller\mpc\MPC.md
  - pid:
    - PID: controller\pid\PID.md
  - rpp:
    - RPP: controller\rpp\RPP.md
- planner:
  - evolutionary_search:
    - aco:
      - ACO: planner\evolutionary_search\aco\ACO.md
    - pso:
      - PSO: planner\evolutionary_search\pso\PSO.md
  - graph_search:
    - a_star:
      - AStar: planner\graph_search\a_star\AStar.md
    - bi_a_star:
      - BiAStar: planner\graph_search\bi_a_star\BiAStar.md
    - d_star:
      - DNode: planner\graph_search\d_star\DNode.md
      - DStar: planner\graph_search\d_star\DStar.md
    - d_star_lite:
      - DStarLite: planner\graph_search\d_star_lite\DStarLite.md
    - dijkstra:
      - Dijkstra: planner\graph_search\dijkstra\Dijkstra.md
    - gbfs:
      - GBFS: planner\graph_search\gbfs\GBFS.md
    - jps:
      - JPS: planner\graph_search\jps\JPS.md
    - lazy_theta_star:
      - LazyThetaStar: planner\graph_search\lazy_theta_star\LazyThetaStar.md
    - lpa_star:
      - LNode: planner\graph_search\lpa_star\LNode.md
      - LPAStar: planner\graph_search\lpa_star\LPAStar.md
    - s_theta_star:
      - SThetaStar: planner\graph_search\s_theta_star\SThetaStar.md
    - theta_star:
      - ThetaStar: planner\graph_search\theta_star\ThetaStar.md
    - voronoi:
      - VoronoiPlanner: planner\graph_search\voronoi\VoronoiPlanner.md
  - planner:
    - PathPlanner: planner\planner\PathPlanner.md
  - planner_factory:
    - PathPlannerFactory: planner\planner_factory\PathPlannerFactory.md
  - sample_search:
    - informed_rrt:
      - ellipse: planner\sample_search\informed_rrt\ellipse.md
      - InformedRRT: planner\sample_search\informed_rrt\InformedRRT.md
    - rrt:
      - RRT: planner\sample_search\rrt\RRT.md
    - rrt_connect:
      - RRTConnect: planner\sample_search\rrt_connect\RRTConnect.md
    - rrt_star:
      - RRTStar: planner\sample_search\rrt_star\RRTStar.md
plugins:
- search
- autorefs
- mike:
    alias_type: symlink
    version_selector: true
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths:
        - pykit_tools
        options:
          heading_level: 2
          show_root_heading: true
          show_symbol_type: true
          show_symbol_type_toc: true
          show_symbol_type_heading: true
          show_source: true
          show_submodules: true
        selection:
          docstring_style: google
extra:
  version:
    provider: mike
    default: latest
    alias: true
