a_star:
  heuristic_type: euclidean

dijkstra:
  heuristic_type: euclidean

gbfs:
  heuristic_type: euclidean

bi_a_star:
  heuristic_type: euclidean

theta_star:
  heuristic_type: euclidean

lazy_theta_star:
  heuristic_type: euclidean

s_theta_star:
  heuristic_type: euclidean

jps:
  heuristic_type: euclidean

voronoi:
  heuristic_type: euclidean
  # number of edges from one sampled point
  n_knn: 4
  # maximum edge length
  max_edge_len: 10.0
  # inflation range
  inflation_r: 1.0

d_star:
  heuristic_type: euclidean

lpa_star:
  heuristic_type: euclidean

d_star_lite:
  heuristic_type: euclidean

rrt:
  # Maximum expansion distance one step
  max_dist: 0.5
  # Maximum number of sample points
  sample_num: 10000
  # heuristic sample ratio for goal
  goal_sample_rate: 0.05
  # inflation bias
  delta: 0.5

rrt_connect:
  max_dist: 0.5
  sample_num: 10000
  goal_sample_rate: 0.05
  delta: 0.5

rrt_star:
  max_dist: 0.5
  sample_num: 10000
  goal_sample_rate: 0.05
  delta: 0.5
  # optimization radius
  r: 10

informed_rrt:
  max_dist: 0.5
  sample_num: 2000
  goal_sample_rate: 0.05
  delta: 0.5
  r: 12