agents:
  - start: !!python/tuple [5, 5, 0.0]
    goal: !!python/tuple [45, 25, 0]
  # - start: !!python/tuple [60, 60, 0]
  #   goal: !!python/tuple [100, 90, 0]
    name: agent0
    type: differential

strategy:
  planner:
    name: "a_star"
    ## a_star
    ## dijkstra
    ## gbfs
    ## bi_a_star
    ## theta_star
    ## lazy_theta_star
    ## s_theta_star
    ## jps
    ## voronoi
    ## d_star
    ## lpa_star
    ## d_star_lite
    ## rrt
    ## rrt_connect
    ## rrt_star
    ## informed_rrt

    config: "../../planner_params/path_planner.yaml"

    ## pso
    # config: "../../planner_params/evolutionary_search.yaml"

  controller:
    name: "rpp"
    config: "../../controller_params/controller.yaml"

grid_map:
  # file: "../../maps/warehouse.png"
  file: ""
  resolution: 0.5
  dimensions: [51, 31]
  obstacles:
    - !!python/tuple [0, 0]
    - !!python/tuple [0, 1]
    - !!python/tuple [0, 2]
    - !!python/tuple [0, 3]
    - !!python/tuple [0, 4]
    - !!python/tuple [0, 5]
    - !!python/tuple [0, 6]
    - !!python/tuple [0, 7]
    - !!python/tuple [0, 8]
    - !!python/tuple [0, 9]
    - !!python/tuple [0, 10]
    - !!python/tuple [0, 11]
    - !!python/tuple [0, 12]
    - !!python/tuple [0, 13]
    - !!python/tuple [0, 14]
    - !!python/tuple [0, 15]
    - !!python/tuple [0, 16]
    - !!python/tuple [0, 17]
    - !!python/tuple [0, 18]
    - !!python/tuple [0, 19]
    - !!python/tuple [0, 20]
    - !!python/tuple [0, 21]
    - !!python/tuple [0, 22]
    - !!python/tuple [0, 23]
    - !!python/tuple [0, 24]
    - !!python/tuple [0, 25]
    - !!python/tuple [0, 26]
    - !!python/tuple [0, 27]
    - !!python/tuple [0, 28]
    - !!python/tuple [0, 29]
    - !!python/tuple [0, 30]
    - !!python/tuple [50, 0]
    - !!python/tuple [50, 1]
    - !!python/tuple [50, 2]
    - !!python/tuple [50, 3]
    - !!python/tuple [50, 4]
    - !!python/tuple [50, 5]
    - !!python/tuple [50, 6]
    - !!python/tuple [50, 7]
    - !!python/tuple [50, 8]
    - !!python/tuple [50, 9]
    - !!python/tuple [50, 10]
    - !!python/tuple [50, 11]
    - !!python/tuple [50, 12]
    - !!python/tuple [50, 13]
    - !!python/tuple [50, 14]
    - !!python/tuple [50, 15]
    - !!python/tuple [50, 16]
    - !!python/tuple [50, 17]
    - !!python/tuple [50, 18]
    - !!python/tuple [50, 19]
    - !!python/tuple [50, 20]
    - !!python/tuple [50, 21]
    - !!python/tuple [50, 22]
    - !!python/tuple [50, 23]
    - !!python/tuple [50, 24]
    - !!python/tuple [50, 25]
    - !!python/tuple [50, 26]
    - !!python/tuple [50, 27]
    - !!python/tuple [50, 28]
    - !!python/tuple [50, 29]
    - !!python/tuple [50, 30]
    - !!python/tuple [0, 0]
    - !!python/tuple [1, 0]
    - !!python/tuple [2, 0]
    - !!python/tuple [3, 0]
    - !!python/tuple [4, 0]
    - !!python/tuple [5, 0]
    - !!python/tuple [6, 0]
    - !!python/tuple [7, 0]
    - !!python/tuple [8, 0]
    - !!python/tuple [9, 0]
    - !!python/tuple [10, 0]
    - !!python/tuple [11, 0]
    - !!python/tuple [12, 0]
    - !!python/tuple [13, 0]
    - !!python/tuple [14, 0]
    - !!python/tuple [15, 0]
    - !!python/tuple [16, 0]
    - !!python/tuple [17, 0]
    - !!python/tuple [18, 0]
    - !!python/tuple [19, 0]
    - !!python/tuple [20, 0]
    - !!python/tuple [21, 0]
    - !!python/tuple [22, 0]
    - !!python/tuple [23, 0]
    - !!python/tuple [24, 0]
    - !!python/tuple [25, 0]
    - !!python/tuple [26, 0]
    - !!python/tuple [27, 0]
    - !!python/tuple [28, 0]
    - !!python/tuple [29, 0]
    - !!python/tuple [30, 0]
    - !!python/tuple [31, 0]
    - !!python/tuple [32, 0]
    - !!python/tuple [33, 0]
    - !!python/tuple [34, 0]
    - !!python/tuple [35, 0]
    - !!python/tuple [36, 0]
    - !!python/tuple [37, 0]
    - !!python/tuple [38, 0]
    - !!python/tuple [39, 0]
    - !!python/tuple [40, 0]
    - !!python/tuple [41, 0]
    - !!python/tuple [42, 0]
    - !!python/tuple [43, 0]
    - !!python/tuple [44, 0]
    - !!python/tuple [45, 0]
    - !!python/tuple [46, 0]
    - !!python/tuple [47, 0]
    - !!python/tuple [48, 0]
    - !!python/tuple [49, 0]
    - !!python/tuple [50, 0]
    - !!python/tuple [0, 30]
    - !!python/tuple [1, 30]
    - !!python/tuple [2, 30]
    - !!python/tuple [3, 30]
    - !!python/tuple [4, 30]
    - !!python/tuple [5, 30]
    - !!python/tuple [6, 30]
    - !!python/tuple [7, 30]
    - !!python/tuple [8, 30]
    - !!python/tuple [9, 30]
    - !!python/tuple [10, 30]
    - !!python/tuple [11, 30]
    - !!python/tuple [12, 30]
    - !!python/tuple [13, 30]
    - !!python/tuple [14, 30]
    - !!python/tuple [15, 30]
    - !!python/tuple [16, 30]
    - !!python/tuple [17, 30]
    - !!python/tuple [18, 30]
    - !!python/tuple [19, 30]
    - !!python/tuple [20, 30]
    - !!python/tuple [21, 30]
    - !!python/tuple [22, 30]
    - !!python/tuple [23, 30]
    - !!python/tuple [24, 30]
    - !!python/tuple [25, 30]
    - !!python/tuple [26, 30]
    - !!python/tuple [27, 30]
    - !!python/tuple [28, 30]
    - !!python/tuple [29, 30]
    - !!python/tuple [30, 30]
    - !!python/tuple [31, 30]
    - !!python/tuple [32, 30]
    - !!python/tuple [33, 30]
    - !!python/tuple [34, 30]
    - !!python/tuple [35, 30]
    - !!python/tuple [36, 30]
    - !!python/tuple [37, 30]
    - !!python/tuple [38, 30]
    - !!python/tuple [39, 30]
    - !!python/tuple [40, 30]
    - !!python/tuple [41, 30]
    - !!python/tuple [42, 30]
    - !!python/tuple [43, 30]
    - !!python/tuple [44, 30]
    - !!python/tuple [45, 30]
    - !!python/tuple [46, 30]
    - !!python/tuple [47, 30]
    - !!python/tuple [48, 30]
    - !!python/tuple [49, 30]
    - !!python/tuple [50, 30]
    # user-define
    - !!python/tuple [10, 15]
    - !!python/tuple [11, 15]
    - !!python/tuple [12, 15]
    - !!python/tuple [13, 15]
    - !!python/tuple [14, 15]
    - !!python/tuple [15, 15]
    - !!python/tuple [16, 15]
    - !!python/tuple [17, 15]
    - !!python/tuple [18, 15]
    - !!python/tuple [19, 15]
    - !!python/tuple [20, 15]

    - !!python/tuple [20, 0]
    - !!python/tuple [20, 1]
    - !!python/tuple [20, 2]
    - !!python/tuple [20, 3]
    - !!python/tuple [20, 4]
    - !!python/tuple [20, 5]
    - !!python/tuple [20, 6]
    - !!python/tuple [20, 7]
    - !!python/tuple [20, 8]
    - !!python/tuple [20, 9]
    - !!python/tuple [20, 10]
    - !!python/tuple [20, 11]
    - !!python/tuple [20, 12]
    - !!python/tuple [20, 13]
    - !!python/tuple [20, 14]
    - !!python/tuple [20, 15]

    - !!python/tuple [30, 15]
    - !!python/tuple [30, 16]
    - !!python/tuple [30, 17]
    - !!python/tuple [30, 18]
    - !!python/tuple [30, 19]
    - !!python/tuple [30, 20]
    - !!python/tuple [30, 21]
    - !!python/tuple [30, 22]
    - !!python/tuple [30, 23]
    - !!python/tuple [30, 24]
    - !!python/tuple [30, 25]
    - !!python/tuple [30, 26]
    - !!python/tuple [30, 27]
    - !!python/tuple [30, 28]
    - !!python/tuple [30, 29]

    - !!python/tuple [40, 0]
    - !!python/tuple [40, 1]
    - !!python/tuple [40, 2]
    - !!python/tuple [40, 3]
    - !!python/tuple [40, 4]
    - !!python/tuple [40, 5]
    - !!python/tuple [40, 6]
    - !!python/tuple [40, 7]
    - !!python/tuple [40, 8]
    - !!python/tuple [40, 9]
    - !!python/tuple [40, 10]
    - !!python/tuple [40, 11]
    - !!python/tuple [40, 12]
    - !!python/tuple [40, 13]
    - !!python/tuple [40, 14]
    - !!python/tuple [40, 15]